# Generated by Django 2.2.5 on 2019-11-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TotalAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('gu', models.CharField(blank=True, max_length=100, null=True)),
                ('dong', models.CharField(blank=True, max_length=100, null=True)),
                ('mac_score', models.FloatField(blank=True, default=0.0, null=True)),
                ('lot_score', models.FloatField(blank=True, default=0.0, null=True)),
                ('burgerking_score', models.FloatField(blank=True, default=0.0, null=True)),
                ('seveneleven_score', models.FloatField(blank=True, default=0.0, null=True)),
                ('cu_score', models.FloatField(blank=True, default=0.0, null=True)),
                ('gs25_score', models.FloatField(blank=True, default=0.0, null=True)),
                ('starbucks_score', models.FloatField(blank=True, default=0.0, null=True)),
                ('lottecinema_score', models.FloatField(blank=True, default=0.0, null=True)),
                ('megabox_score', models.FloatField(blank=True, default=0.0, null=True)),
                ('cgv_score', models.FloatField(blank=True, default=0.0, null=True)),
                ('total_score', models.FloatField(blank=True, default=0.0, null=True)),
                ('high_oil', models.FloatField(blank=True, default=0.0, null=True)),
                ('oil', models.FloatField(blank=True, default=0.0, null=True)),
                ('oil2', models.FloatField(blank=True, default=0.0, null=True)),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
                ('catch', models.IntegerField(blank=True, default=0, null=True)),
                ('percent', models.FloatField(blank=True, default=0.0, null=True)),
                ('mac_count', models.IntegerField(blank=True, default=0, null=True)),
                ('lot_count', models.IntegerField(blank=True, default=0, null=True)),
                ('burgerking_count', models.IntegerField(blank=True, default=0, null=True)),
                ('seveneleven_count', models.IntegerField(blank=True, default=0, null=True)),
                ('cu_count', models.IntegerField(blank=True, default=0, null=True)),
                ('gs25_count', models.IntegerField(blank=True, default=0, null=True)),
                ('starbucks_count', models.IntegerField(blank=True, default=0, null=True)),
                ('lottecinema_count', models.IntegerField(blank=True, default=0, null=True)),
                ('megabox_count', models.IntegerField(blank=True, default=0, null=True)),
                ('cgv_count', models.IntegerField(blank=True, default=0, null=True)),
                ('total_count', models.IntegerField(blank=True, default=0, null=True)),
                ('first', models.CharField(blank=True, max_length=100, null=True)),
                ('second', models.CharField(blank=True, max_length=100, null=True)),
                ('third', models.CharField(blank=True, max_length=100, null=True)),
                ('first_mapx', models.FloatField(blank=True, default=0.0, null=True)),
                ('first_mapy', models.FloatField(blank=True, default=0.0, null=True)),
                ('second_mapx', models.FloatField(blank=True, default=0.0, null=True)),
                ('second_mapy', models.FloatField(blank=True, default=0.0, null=True)),
                ('third_mapx', models.FloatField(blank=True, default=0.0, null=True)),
                ('third_mapy', models.FloatField(blank=True, default=0.0, null=True)),
                ('elementary_count', models.IntegerField(blank=True, default=0, null=True)),
                ('middle_count', models.IntegerField(blank=True, default=0, null=True)),
                ('high_count', models.IntegerField(blank=True, default=0, null=True)),
                ('park_count', models.IntegerField(blank=True, default=0, null=True)),
                ('station', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
